del %WWFLAT%\lib\AUDIO.lib
del %WWFLAT%\lib\descmgmt.lib
del %WWFLAT%\lib\dipthong.lib
del %WWFLAT%\lib\file.lib
del %WWFLAT%\lib\font.lib
del %WWFLAT%\lib\iff.lib
del %WWFLAT%\lib\keyboard.lib
del %WWFLAT%\lib\mcgaprim.lib
del %WWFLAT%\lib\mem.lib
del %WWFLAT%\lib\misc.lib
del %WWFLAT%\lib\mono.lib
del %WWFLAT%\lib\palette.lib
del %WWFLAT%\lib\playcd.lib
del %WWFLAT%\lib\shape.lib
del %WWFLAT%\lib\svgaprim.lib
del %WWFLAT%\lib\tile.lib
del %WWFLAT%\lib\timer.lib
del %WWFLAT%\lib\video.lib
del %WWFLAT%\lib\windows.lib
del %WWFLAT%\lib\wsa.lib
del %WWFLAT%\lib\wwflat32.lib
